// MakeMee — Resource data
// Fields: id, name, description, url, type, level, tracks[], phase, subgroup?
// type: 'course' | 'book' | 'youtube' | 'platform' | 'guide'
// level: 'beginner' | 'intermediate' | 'advanced'
// tracks: subset of ['ds', 'ml', 'ai']
// phase: 0=Foundations, 1=Core ML/DS, 2=Deep Learning, 3=AI Engineering, 4=Practice

const RESOURCES = [

  // ── Phase 0 · Python ────────────────────────────────────────────────────
  {
    id: 'brocode-python',
    name: 'Python Full Course for Beginners — Bro Code',
    description: '12-hour single-video Python course. Casual, fast-paced, and comprehensive. Great alternative to CS50P if you prefer video lectures.',
    url: 'https://www.youtube.com/watch?v=XKHEtdqhLK8',
    type: 'youtube',
    level: 'beginner',
    tracks: ['ds', 'ml', 'ai'],
    phase: 0,
    subgroup: 'python',
  },
  {
    id: 'cs50p',
    name: "CS50's Introduction to Programming with Python",
    description: "Harvard's gold-standard free Python course. Covers functions, OOP, file I/O, libraries, and testing. The best starting point.",
    url: 'https://cs50.harvard.edu/python/',
    type: 'course',
    level: 'beginner',
    tracks: ['ds', 'ml', 'ai'],
    phase: 0,
    subgroup: 'python',
  },
  {
    id: 'learnpython',
    name: 'LearnPython.org',
    description: 'Interactive Python tutorials directly in the browser. Ideal for drilling syntax, data structures, and the standard library fast.',
    url: 'https://www.learnpython.org/',
    type: 'platform',
    level: 'beginner',
    tracks: ['ds', 'ml', 'ai'],
    phase: 0,
    subgroup: 'python',
  },

  // ── Phase 0 · Mathematics ───────────────────────────────────────────────
  {
    id: 'khan-linalg',
    name: 'Khan Academy — Linear Algebra',
    description: 'Thorough, free linear algebra from the ground up. Vectors, matrices, transformations, and eigenvalues — the language ML runs on.',
    url: 'https://www.khanacademy.org/math/linear-algebra',
    type: 'course',
    level: 'beginner',
    tracks: ['ds', 'ml', 'ai'],
    phase: 0,
    subgroup: 'math',
  },
  {
    id: 'mit-18-06',
    name: 'MIT OCW 18.06 — Linear Algebra (Gilbert Strang)',
    description: 'The legendary MIT linear algebra course. Widely considered the definitive treatment of the subject. Free and timeless.',
    url: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/',
    type: 'course',
    level: 'intermediate',
    tracks: ['ds', 'ml', 'ai'],
    phase: 0,
    subgroup: 'math',
  },
  {
    id: 'dlai-math',
    name: 'Mathematics for ML & Data Science — DeepLearning.AI',
    description: 'Covers linear algebra, calculus, probability and statistics with Python labs. Free audit on Coursera.',
    url: 'https://www.deeplearning.ai/courses/mathematics-for-machine-learning-and-data-science-specialization/',
    type: 'course',
    level: 'beginner',
    tracks: ['ds', 'ml', 'ai'],
    phase: 0,
    subgroup: 'math',
  },

  // ── Phase 1 · Core ML & Data Science ────────────────────────────────────
  {
    id: 'brocode-mysql',
    name: 'MySQL Full Course — Bro Code',
    description: '3-hour intro to MySQL: tables, queries, joins, and stored procedures. Practical SQL foundation for data work.',
    url: 'https://www.youtube.com/watch?v=5OdVJbNCSso',
    type: 'youtube',
    level: 'beginner',
    tracks: ['ds'],
    phase: 1,
  },
  {
    id: 'kaggle-learn',
    name: 'Kaggle Learn',
    description: 'Free micro-courses: Intro to ML, Pandas, Feature Engineering, SQL. Each takes a few hours — immediate hands-on practice.',
    url: 'https://www.kaggle.com/learn',
    type: 'platform',
    level: 'beginner',
    tracks: ['ds', 'ml'],
    phase: 1,
  },
  {
    id: 'ng-ai-everyone',
    name: 'AI for Everyone — Andrew Ng (Coursera)',
    description: 'Non-technical grounding in AI capabilities, limitations, and strategy. Essential mental model before going deep. Free audit.',
    url: 'https://www.coursera.org/learn/ai-for-everyone',
    type: 'course',
    level: 'beginner',
    tracks: ['ds', 'ml', 'ai'],
    phase: 1,
  },
  {
    id: 'mit-6036',
    name: 'MIT OCW 6.036 — Introduction to Machine Learning',
    description: 'MIT undergrad ML course. Classification, regression, neural nets, SVMs, Markov models. Rigorous and completely free.',
    url: 'https://ocw.mit.edu/courses/6-036-introduction-to-machine-learning-fall-2020/',
    type: 'course',
    level: 'intermediate',
    tracks: ['ds', 'ml'],
    phase: 1,
  },
  {
    id: 'statquest',
    name: 'StatQuest with Josh Starmer',
    description: 'The clearest explanations of statistics and ML algorithms on YouTube. Intimidating formulas turned into genuine intuition.',
    url: 'https://www.youtube.com/@statquest',
    type: 'youtube',
    level: 'beginner',
    tracks: ['ds', 'ml'],
    phase: 1,
  },

  // ── Phase 2 · Deep Learning ─────────────────────────────────────────────
  {
    id: '3b1b-neural',
    name: '3Blue1Brown — Neural Networks',
    description: 'The best visual introduction to neural networks. Animated, intuitive, and free. Watch before anything else in this phase.',
    url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
    type: 'youtube',
    level: 'beginner',
    tracks: ['ml', 'ai'],
    phase: 2,
  },
  {
    id: 'fastai-course',
    name: 'fast.ai — Practical Deep Learning for Coders',
    description: 'Top-down: build real applications first, learn theory second. Uses PyTorch. The most practical deep learning course available.',
    url: 'https://course.fast.ai/',
    type: 'course',
    level: 'intermediate',
    tracks: ['ml', 'ai'],
    phase: 2,
  },
  {
    id: 'fastai-book',
    name: 'fast.ai — Deep Learning for Coders (Book)',
    description: 'Free companion textbook to the fast.ai course. Deep dives into vision, NLP, tabular, and collaborative filtering.',
    url: 'https://fastai.github.io/fastbook2e/',
    type: 'book',
    level: 'intermediate',
    tracks: ['ml', 'ai'],
    phase: 2,
  },
  {
    id: 'dlai-dl-spec',
    name: 'Deep Learning Specialization — Andrew Ng (Coursera)',
    description: '5-course series: NNs, hyperparameter tuning, ML strategy, CNNs, and RNNs/sequence models. Free audit available.',
    url: 'https://www.coursera.org/specializations/deep-learning',
    type: 'course',
    level: 'intermediate',
    tracks: ['ml', 'ai'],
    phase: 2,
  },
  {
    id: 'karpathy-zero',
    name: 'Neural Networks: Zero to Hero — Andrej Karpathy',
    description: 'Build backpropagation, then a GPT, from scratch in pure Python. The most hands-on deep learning series in existence.',
    url: 'https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ',
    type: 'youtube',
    level: 'advanced',
    tracks: ['ml', 'ai'],
    phase: 2,
  },

  // ── Phase 3 · AI Engineering ─────────────────────────────────────────────
  {
    id: 'pe-guide',
    name: 'Prompt Engineering Guide',
    description: 'Comprehensive reference: zero/few-shot, chain-of-thought, RAG, function calling, and agentic system patterns.',
    url: 'https://www.promptingguide.ai/',
    type: 'guide',
    level: 'intermediate',
    tracks: ['ai'],
    phase: 3,
  },
  {
    id: 'dlai-short',
    name: 'DeepLearning.AI Short Courses',
    description: '68+ free courses: LangChain, RAG, fine-tuning, agents, vector databases, multi-modal systems. Each 1–2 hours.',
    url: 'https://www.deeplearning.ai/courses/',
    type: 'course',
    level: 'intermediate',
    tracks: ['ai'],
    phase: 3,
  },
  {
    id: 'coursera-llm',
    name: 'LLM Engineering Specialization (Coursera)',
    description: 'End-to-end LLM engineering: prompting, fine-tuning, optimization, and RAG pipelines. Free audit available.',
    url: 'https://www.coursera.org/specializations/llm-engineering-prompting-fine-tuning-optimization-rag',
    type: 'course',
    level: 'advanced',
    tracks: ['ai'],
    phase: 3,
  },
  {
    id: 'ai-eng-hub',
    name: 'AI Engineering Hub — GitHub',
    description: 'In-depth tutorials on LLMs, RAG pipelines, and production-grade agent systems. Actively maintained.',
    url: 'https://github.com/patchy631/ai-engineering-hub',
    type: 'guide',
    level: 'advanced',
    tracks: ['ai'],
    phase: 3,
  },

  // ── Phase 4 · Practice & Projects ───────────────────────────────────────
  {
    id: 'kaggle',
    name: 'Kaggle',
    description: 'Competitions, public datasets, and community notebooks. The standard platform for building and showcasing an ML portfolio.',
    url: 'https://www.kaggle.com/',
    type: 'platform',
    level: 'intermediate',
    tracks: ['ds', 'ml', 'ai'],
    phase: 4,
  },
  {
    id: 'deep-ml',
    name: 'Deep-ML',
    description: 'LeetCode-style practice for ML and deep learning. Implement algorithms from scratch to internalise the maths.',
    url: 'https://www.deep-ml.com/',
    type: 'platform',
    level: 'intermediate',
    tracks: ['ml', 'ai'],
    phase: 4,
  },
  {
    id: 'lc-ml',
    name: 'LeetCode — Machine Learning 101',
    description: 'Structured ML learning path covering fundamentals for ML engineering interviews. Complements algorithm prep.',
    url: 'https://leetcode.com/explore/featured/card/machine-learning-101',
    type: 'platform',
    level: 'intermediate',
    tracks: ['ml'],
    phase: 4,
  },
  {
    id: 'two-minute',
    name: 'Two Minute Papers',
    description: 'Latest AI research papers distilled into 5–10 minute videos. The best way to stay current without reading full papers.',
    url: 'https://www.youtube.com/@TwoMinutePapers',
    type: 'youtube',
    level: 'advanced',
    tracks: ['ds', 'ml', 'ai'],
    phase: 4,
  },

];
